# -*- coding: utf-8 -*-
"""Nintendo - Option pricing - V2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18m1oxCouV-Atsthb3VZ4S8TDj-lruW0U
"""

# -*- coding: utf-8 -*-
"""
═══════════════════════════════════════════════════════════════════════════════
    CONSEIL EN PRICING D'OPTIONS - NINTENDO (NTDOY)
    Période: Septembre 2015 - Septembre 2025

    Types d'options évalués pour l'investisseur :
    1. Options Européennes (Black-Scholes-Merton)
    2. Options Américaines (Binomial Tree)
    3. Options Bermudéennes (Binomial Tree modifié)
    4. Options Exotiques - Asiatiques (Monte Carlo)
    5. Greeks pour gestion du risque

    Approche personnalisée selon le profil et objectifs d'investissement
═══════════════════════════════════════════════════════════════════════════════
"""

# ═══════════════════════════════════════════════════════════════════════════
# SECTION 1: IMPORTS ET CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════

import numpy as np
import pandas as pd
import yfinance as yf
from scipy.stats import norm
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

# Bibliothèques pour graphiques interactifs
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px

print("=" * 80)
print("  CONSEIL EN PRICING D'OPTIONS - NINTENDO (NTDOY)")
print("=" * 80)
print()

# ═══════════════════════════════════════════════════════════════════════════
# SECTION 2: RÉCUPÉRATION DES DONNÉES NINTENDO
# ═══════════════════════════════════════════════════════════════════════════

print("📥 Téléchargement des données Nintendo...")

ticker = "NTDOY"
start_date = "2015-09-01"
end_date = "2025-09-30"

# Téléchargement des données
nintendo_data = yf.download(ticker, start=start_date, end=end_date, progress=False)
data = nintendo_data['Close']
data.columns = ['Close']

# Prix actuel (dernière observation)
S0 = data['Close'].iloc[-1]

# Calcul de la volatilité historique (annualisée)
returns = np.log(data['Close'] / data['Close'].shift(1))
volatility_hist = returns.std() * np.sqrt(252)

print(f"✅ Données téléchargées: {len(data)} jours de trading")
print(f"   Période: {data.index[0].strftime('%Y-%m-%d')} à {data.index[-1].strftime('%Y-%m-%d')}")
print(f"   Prix actuel (S0): ${S0:.2f}")
print(f"   Volatilité historique (annualisée): {volatility_hist*100:.2f}%")
print()

# Taux sans risque (US Treasury 10Y source : https://www.cnbc.com/quotes/US10Y le 26/11/2025)
r = 0.04  # 4% par défaut, ajustable selon contexte macroéconomique

print(f"   Taux sans risque utilisé: {r*100:.2f}%")
print()

# ═══════════════════════════════════════════════════════════════════════════
# SECTION 3: PROFIL D'INVESTISSEUR - PERSONNALISATION AVANCÉE
# ═══════════════════════════════════════════════════════════════════════════

print("=" * 80)
print("  PERSONNALISATION SELON VOTRE PROFIL D'INVESTISSEUR")
print("=" * 80)
print()

print("📋 ÉTAPE 1: Quel est votre profil d'investisseur?")
print("   1. COUVERTURE (HEDGING) : Vous détenez des actions Nintendo et voulez vous protéger")
print("   2. SPÉCULATION HAUSSIÈRE : Vous anticipez une hausse du prix")
print("   3. SPÉCULATION BAISSIÈRE : Vous anticipez une baisse du prix")
print("   4. GÉNÉRATION DE REVENUS : Vous voulez générer des revenus réguliers (stratégies covered call)")
print("   5. VOLATILITÉ : Vous voulez profiter des variations de volatilité")
print()

# Configuration par défaut (peut être modifiée)
PROFIL_INVESTISSEUR = 2  # SPÉCULATION HAUSSIÈRE par défaut

profils_investisseur = {
    1: {
        'nom': 'COUVERTURE (HEDGING)',
        'strategie_principale': 'Achat de Puts pour protection',
        'options_recommandees': ['Put Européen', 'Put Américain'],
        'horizon_typique': 'Court à Moyen terme (3-6 mois)',
        'delta_target': 'Négatif (protection)',
        'description': 'Minimiser les pertes en cas de baisse du sous-jacent'
    },
    2: {
        'nom': 'SPÉCULATION HAUSSIÈRE',
        'strategie_principale': 'Achat de Calls',
        'options_recommandees': ['Call Européen', 'Call Américain', 'Call Asiatique'],
        'horizon_typique': 'Moyen terme (6-12 mois)',
        'delta_target': 'Positif élevé (>0.5)',
        'description': 'Profiter d\'une hausse anticipée avec effet de levier'
    },
    3: {
        'nom': 'SPÉCULATION BAISSIÈRE',
        'strategie_principale': 'Achat de Puts',
        'options_recommandees': ['Put Européen', 'Put Américain'],
        'horizon_typique': 'Court à Moyen terme (3-9 mois)',
        'delta_target': 'Négatif (<-0.3)',
        'description': 'Profiter d\'une baisse anticipée'
    },
    4: {
        'nom': 'GÉNÉRATION DE REVENUS',
        'strategie_principale': 'Vente de Calls couverts (Covered Calls)',
        'options_recommandees': ['Call Européen OTM', 'Call Bermudéen'],
        'horizon_typique': 'Court terme répété (1-3 mois)',
        'delta_target': 'Légèrement positif (0.3-0.5)',
        'description': 'Collecter des primes en vendant des calls sur actions détenues'
    },
    5: {
        'nom': 'VOLATILITÉ',
        'strategie_principale': 'Straddle/Strangle',
        'options_recommandees': ['Call & Put Européens', 'Options Exotiques'],
        'horizon_typique': 'Court terme (1-3 mois)',
        'delta_target': 'Neutre (proche de 0)',
        'description': 'Profiter des mouvements de prix importants sans direction précise'
    }
}

profil = profils_investisseur[PROFIL_INVESTISSEUR]
print(f"✅ Profil sélectionné: {profil['nom']}")
print(f"   Stratégie principale: {profil['strategie_principale']}")
print(f"   Options recommandées: {', '.join(profil['options_recommandees'])}")
print(f"   Horizon typique: {profil['horizon_typique']}")
print(f"   Description: {profil['description']}")
print()

print("📋 ÉTAPE 2: Définition des paramètres personnalisés")
print()

# Paramètres ajustables selon le profil
if PROFIL_INVESTISSEUR == 1:  # COUVERTURE
    strikes_range = [0.90, 0.95, 1.00]  # OTM, ATM
    maturities_months = [3, 6, 9]
    option_types_focus = ['put']

elif PROFIL_INVESTISSEUR == 2:  # HAUSSIER
    strikes_range = [0.95, 1.00, 1.05, 1.10]  # ATM, légèrement OTM
    maturities_months = [6, 9, 12]
    option_types_focus = ['call']

elif PROFIL_INVESTISSEUR == 3:  # BAISSIER
    strikes_range = [0.90, 0.95, 1.00, 1.05]
    maturities_months = [3, 6, 9]
    option_types_focus = ['put']

elif PROFIL_INVESTISSEUR == 4:  # REVENUS
    strikes_range = [1.00, 1.05, 1.10]  # ATM et OTM (pour vente)
    maturities_months = [1, 2, 3]
    option_types_focus = ['call']

else:  # VOLATILITÉ
    strikes_range = [0.95, 1.00, 1.05]
    maturities_months = [1, 2, 3]
    option_types_focus = ['call', 'put']

# Génération des strikes et maturités
K_multipliers = strikes_range
K_values = [S0 * mult for mult in K_multipliers]
T_values = [m/12 for m in maturities_months]

print(f"   Prix sous-jacent (S0): ${S0:.2f}")
print(f"   Strikes évalués: {[f'${k:.2f}' for k in K_values]}")
print(f"   Maturités évaluées: {maturities_months} mois")
print(f"   Volatilité utilisée: {volatility_hist*100:.2f}% (historique)")
print(f"   Taux sans risque: {r*100:.2f}%")
print()

# ═══════════════════════════════════════════════════════════════════════════
# SECTION 4: MODÈLES DE PRICING - FONCTIONS PRINCIPALES
# ═══════════════════════════════════════════════════════════════════════════

print("=" * 80)
print("  MODÈLES DE PRICING D'OPTIONS")
print("=" * 80)
print()

# ───────────────────────────────────────────────────────────────────────────
# 4.1: Black-Scholes-Merton (Options Européennes)
# ───────────────────────────────────────────────────────────────────────────

def black_scholes_call(S, K, T, r, sigma):
    """Prix d'un call européen selon Black-Scholes-Merton"""
    if T <= 0:
        return max(S - K, 0)
    d1 = (np.log(S / K) + (r + 0.5 * sigma ** 2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    call_price = S * norm.cdf(d1) - K * np.exp(-r * T) * norm.cdf(d2)
    return call_price

def black_scholes_put(S, K, T, r, sigma):
    """Prix d'un put européen selon Black-Scholes-Merton"""
    if T <= 0:
        return max(K - S, 0)
    d1 = (np.log(S / K) + (r + 0.5 * sigma ** 2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)
    put_price = K * np.exp(-r * T) * norm.cdf(-d2) - S * norm.cdf(-d1)
    return put_price

# Greeks pour Black-Scholes
def bs_greeks(S, K, T, r, sigma, option_type='call'):
    """Calcul des Greeks (Delta, Gamma, Vega, Theta, Rho)"""
    if T <= 0:
        return {'delta': 0, 'gamma': 0, 'vega': 0, 'theta': 0, 'rho': 0}

    d1 = (np.log(S / K) + (r + 0.5 * sigma ** 2) * T) / (sigma * np.sqrt(T))
    d2 = d1 - sigma * np.sqrt(T)

    if option_type == 'call':
        delta = norm.cdf(d1)
        theta = (-(S * norm.pdf(d1) * sigma) / (2 * np.sqrt(T))
                 - r * K * np.exp(-r * T) * norm.cdf(d2)) / 365
        rho = K * T * np.exp(-r * T) * norm.cdf(d2) / 100
    else:  # put
        delta = -norm.cdf(-d1)
        theta = (-(S * norm.pdf(d1) * sigma) / (2 * np.sqrt(T))
                 + r * K * np.exp(-r * T) * norm.cdf(-d2)) / 365
        rho = -K * T * np.exp(-r * T) * norm.cdf(-d2) / 100

    gamma = norm.pdf(d1) / (S * sigma * np.sqrt(T))
    vega = S * norm.pdf(d1) * np.sqrt(T) / 100

    return {
        'delta': delta,
        'gamma': gamma,
        'vega': vega,
        'theta': theta,
        'rho': rho
    }

# ───────────────────────────────────────────────────────────────────────────
# 4.2: Binomial Tree (Options Américaines et Bermudéennes)
# ───────────────────────────────────────────────────────────────────────────

def binomial_tree_american(S, K, T, r, sigma, N, option_type='call'):
    """
    Prix d'une option américaine par arbre binomial
    N: nombre de périodes
    """
    dt = T / N
    u = np.exp(sigma * np.sqrt(dt))
    d = 1 / u
    p = (np.exp(r * dt) - d) / (u - d)

    # Initialisation de l'arbre des prix
    stock_tree = np.zeros((N + 1, N + 1))
    option_tree = np.zeros((N + 1, N + 1))

    # Prix du sous-jacent à maturité
    for i in range(N + 1):
        stock_tree[i, N] = S * (u ** (N - i)) * (d ** i)

    # Valeur intrinsèque à maturité
    for i in range(N + 1):
        if option_type == 'call':
            option_tree[i, N] = max(stock_tree[i, N] - K, 0)
        else:
            option_tree[i, N] = max(K - stock_tree[i, N], 0)

    # Backward induction
    for j in range(N - 1, -1, -1):
        for i in range(j + 1):
            stock_tree[i, j] = S * (u ** (j - i)) * (d ** i)

            # Valeur de continuation (discounted expected value)
            continuation = np.exp(-r * dt) * (p * option_tree[i, j + 1] +
                                               (1 - p) * option_tree[i + 1, j + 1])

            # Valeur d'exercice immédiat
            if option_type == 'call':
                exercise = max(stock_tree[i, j] - K, 0)
            else:
                exercise = max(K - stock_tree[i, j], 0)

            # Pour une option américaine: max(continuation, exercise)
            option_tree[i, j] = max(continuation, exercise)

    return option_tree[0, 0]

def binomial_tree_bermudan(S, K, T, r, sigma, N, exercise_dates, option_type='call'):
    """
    Prix d'une option bermudéenne par arbre binomial
    exercise_dates: liste des indices de périodes où l'exercice est permis
    """
    dt = T / N
    u = np.exp(sigma * np.sqrt(dt))
    d = 1 / u
    p = (np.exp(r * dt) - d) / (u - d)

    stock_tree = np.zeros((N + 1, N + 1))
    option_tree = np.zeros((N + 1, N + 1))

    # Prix du sous-jacent à maturité
    for i in range(N + 1):
        stock_tree[i, N] = S * (u ** (N - i)) * (d ** i)

    # Valeur intrinsèque à maturité
    for i in range(N + 1):
        if option_type == 'call':
            option_tree[i, N] = max(stock_tree[i, N] - K, 0)
        else:
            option_tree[i, N] = max(K - stock_tree[i, N], 0)

    # Backward induction
    for j in range(N - 1, -1, -1):
        for i in range(j + 1):
            stock_tree[i, j] = S * (u ** (j - i)) * (d ** i)

            continuation = np.exp(-r * dt) * (p * option_tree[i, j + 1] +
                                               (1 - p) * option_tree[i + 1, j + 1])

            if option_type == 'call':
                exercise = max(stock_tree[i, j] - K, 0)
            else:
                exercise = max(K - stock_tree[i, j], 0)

            # Exercice possible seulement aux dates bermudéennes
            if j in exercise_dates:
                option_tree[i, j] = max(continuation, exercise)
            else:
                option_tree[i, j] = continuation

    return option_tree[0, 0]

# ───────────────────────────────────────────────────────────────────────────
# 4.3: Monte Carlo (Options Asiatiques)
# ───────────────────────────────────────────────────────────────────────────

def asian_option_monte_carlo(S, K, T, r, sigma, n_simulations=50000, n_steps=252, option_type='call'):
    """
    Prix d'une option asiatique (moyenne arithmétique) par Monte Carlo
    """
    dt = T / n_steps
    discount_factor = np.exp(-r * T)

    payoffs = []

    for _ in range(n_simulations):
        # Simulation du chemin du prix
        prices = [S]
        for _ in range(n_steps):
            z = np.random.standard_normal()
            S_next = prices[-1] * np.exp((r - 0.5 * sigma**2) * dt + sigma * np.sqrt(dt) * z)
            prices.append(S_next)

        # Prix moyen
        avg_price = np.mean(prices)

        # Payoff
        if option_type == 'call':
            payoff = max(avg_price - K, 0)
        else:
            payoff = max(K - avg_price, 0)

        payoffs.append(payoff)

    # Prix de l'option
    option_price = discount_factor * np.mean(payoffs)
    std_error = discount_factor * np.std(payoffs) / np.sqrt(n_simulations)

    return option_price, std_error

print("✅ Modèles de pricing implémentés:")
print("   - Black-Scholes-Merton (Options Européennes)")
print("   - Arbre Binomial (Options Américaines)")
print("   - Arbre Binomial modifié (Options Bermudéennes)")
print("   - Monte Carlo (Options Asiatiques)")
print("   - Greeks (Delta, Gamma, Vega, Theta, Rho)")
print()

# ═══════════════════════════════════════════════════════════════════════════
# SECTION 5: ÉVALUATION DES OPTIONS SELON LE PROFIL
# ═══════════════════════════════════════════════════════════════════════════

print("=" * 80)
print(f"  ÉVALUATION DES OPTIONS - PROFIL {profil['nom']}")
print("=" * 80)
print()

# Dataframe pour stocker tous les résultats
results_all = []

for K in K_values:
    for T in T_values:
        T_months = int(T * 12)
        moneyness = S0 / K

        # Déterminer si ITM, ATM, OTM
        if moneyness > 1.05:
            status = 'ITM'
        elif moneyness > 0.95:
            status = 'ATM'
        else:
            status = 'OTM'

        result = {
            'Strike': K,
            'Maturité (mois)': T_months,
            'Maturité (années)': T,
            'Moneyness': moneyness,
            'Status': status
        }

        # ───────────────────────────────────────────────────────────
        # Évaluation selon les types d'options recommandés
        # ───────────────────────────────────────────────────────────

        if 'call' in option_types_focus:
            # Call Européen
            call_euro = black_scholes_call(S0, K, T, r, volatility_hist)
            result['Call Européen'] = call_euro

            # Call Américain
            call_american = binomial_tree_american(S0, K, T, r, volatility_hist, N=100, option_type='call')
            result['Call Américain'] = call_american

            # Call Bermudéen (exercice possible tous les 3 mois)
            n_steps = 100
            exercise_frequency = max(1, int(n_steps * 3 / (T * 12)))
            exercise_dates_berm = list(range(0, n_steps + 1, exercise_frequency))
            call_bermudan = binomial_tree_bermudan(S0, K, T, r, volatility_hist, N=n_steps,
                                                   exercise_dates=exercise_dates_berm, option_type='call')
            result['Call Bermudéen'] = call_bermudan

            # Call Asiatique
            call_asian, call_asian_se = asian_option_monte_carlo(S0, K, T, r, volatility_hist,
                                                                   n_simulations=30000, option_type='call')
            result['Call Asiatique'] = call_asian

            # Greeks pour Call Européen
            greeks_call = bs_greeks(S0, K, T, r, volatility_hist, 'call')
            result['Call Delta'] = greeks_call['delta']
            result['Call Gamma'] = greeks_call['gamma']
            result['Call Vega'] = greeks_call['vega']
            result['Call Theta'] = greeks_call['theta']

        if 'put' in option_types_focus:
            # Put Européen
            put_euro = black_scholes_put(S0, K, T, r, volatility_hist)
            result['Put Européen'] = put_euro

            # Put Américain
            put_american = binomial_tree_american(S0, K, T, r, volatility_hist, N=100, option_type='put')
            result['Put Américain'] = put_american

            # Put Bermudéen
            n_steps = 100
            exercise_frequency = max(1, int(n_steps * 3 / (T * 12)))
            exercise_dates_berm = list(range(0, n_steps + 1, exercise_frequency))
            put_bermudan = binomial_tree_bermudan(S0, K, T, r, volatility_hist, N=n_steps,
                                                  exercise_dates=exercise_dates_berm, option_type='put')
            result['Put Bermudéen'] = put_bermudan

            # Put Asiatique
            put_asian, put_asian_se = asian_option_monte_carlo(S0, K, T, r, volatility_hist,
                                                                 n_simulations=30000, option_type='put')
            result['Put Asiatique'] = put_asian

            # Greeks pour Put Européen
            greeks_put = bs_greeks(S0, K, T, r, volatility_hist, 'put')
            result['Put Delta'] = greeks_put['delta']
            result['Put Gamma'] = greeks_put['gamma']
            result['Put Vega'] = greeks_put['vega']
            result['Put Theta'] = greeks_put['theta']

        results_all.append(result)

# Conversion en DataFrame
df_results = pd.DataFrame(results_all)

print(f"✅ {len(df_results)} configurations d'options évaluées")
print()
print("📊 APERÇU DES RÉSULTATS (premières lignes):")
print("-" * 80)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 120)
print(df_results.head(10).to_string(index=False))
print()

# ═══════════════════════════════════════════════════════════════════════════
# SECTION 6: VISUALISATIONS INTERACTIVES
# ═══════════════════════════════════════════════════════════════════════════

print("=" * 80)
print("  VISUALISATIONS INTERACTIVES")
print("=" * 80)
print()

# ───────────────────────────────────────────────────────────────────────────
# 6.1: Prix des options selon Strike et Maturité
# ───────────────────────────────────────────────────────────────────────────

if 'call' in option_types_focus:
    # Surface 3D pour Calls Européens
    strikes_unique = sorted(df_results['Strike'].unique())
    maturities_unique = sorted(df_results['Maturité (années)'].unique())

    Z_call = []
    for T in maturities_unique:
        row = []
        for K in strikes_unique:
            val = df_results[(df_results['Strike'] == K) &
                            (df_results['Maturité (années)'] == T)]['Call Européen'].values
            row.append(val[0] if len(val) > 0 else 0)
        Z_call.append(row)

    fig_3d_call = go.Figure(data=[go.Surface(
        x=strikes_unique,
        y=maturities_unique,
        z=Z_call,
        colorscale='Viridis',
        colorbar=dict(title="Prix Call")
    )])

    fig_3d_call.update_layout(
        title=f'Prix Call Européen - Surface 3D<br>Profil {profil["nom"]}',
        scene=dict(
            xaxis_title='Strike ($)',
            yaxis_title='Maturité (années)',
            zaxis_title='Prix de l\'option ($)'
        ),
        height=700
    )

    fig_3d_call.show()
    print("📊 Graphique interactif: Surface 3D Call Européen générée")

if 'put' in option_types_focus:
    # Surface 3D pour Puts Européens
    Z_put = []
    for T in maturities_unique:
        row = []
        for K in strikes_unique:
            val = df_results[(df_results['Strike'] == K) &
                            (df_results['Maturité (années)'] == T)]['Put Européen'].values
            row.append(val[0] if len(val) > 0 else 0)
        Z_put.append(row)

    fig_3d_put = go.Figure(data=[go.Surface(
        x=strikes_unique,
        y=maturities_unique,
        z=Z_put,
        colorscale='Reds',
        colorbar=dict(title="Prix Put")
    )])

    fig_3d_put.update_layout(
        title=f'Prix Put Européen - Surface 3D<br>Profil {profil["nom"]}',
        scene=dict(
            xaxis_title='Strike ($)',
            yaxis_title='Maturité (années)',
            zaxis_title='Prix de l\'option ($)'
        ),
        height=700
    )

    fig_3d_put.show()
    print("📊 Graphique interactif: Surface 3D Put Européen générée")

print()

# ───────────────────────────────────────────────────────────────────────────
# 6.2: Comparaison des types d'options (Européenne vs Américaine vs Bermudéenne)
# ───────────────────────────────────────────────────────────────────────────

if 'call' in option_types_focus:
    # Filtrer pour une maturité spécifique (6 mois ou la plus proche)
    target_maturity = 6
    closest_maturity = min(maturities_months, key=lambda x: abs(x - target_maturity))
    df_comp = df_results[df_results['Maturité (mois)'] == closest_maturity].copy()

    fig_comp_call = go.Figure()

    fig_comp_call.add_trace(go.Scatter(
        x=df_comp['Strike'],
        y=df_comp['Call Européen'],
        name='Call Européen',
        mode='lines+markers',
        line=dict(color='blue', width=3)
    ))

    fig_comp_call.add_trace(go.Scatter(
        x=df_comp['Strike'],
        y=df_comp['Call Américain'],
        name='Call Américain',
        mode='lines+markers',
        line=dict(color='green', width=3)
    ))

    fig_comp_call.add_trace(go.Scatter(
        x=df_comp['Strike'],
        y=df_comp['Call Bermudéen'],
        name='Call Bermudéen',
        mode='lines+markers',
        line=dict(color='orange', width=3)
    ))

    fig_comp_call.add_trace(go.Scatter(
        x=df_comp['Strike'],
        y=df_comp['Call Asiatique'],
        name='Call Asiatique',
        mode='lines+markers',
        line=dict(color='purple', width=3, dash='dash')
    ))

    fig_comp_call.add_vline(x=S0, line_dash="dash", line_color="red",
                           annotation_text=f"Prix actuel: ${S0:.2f}")

    fig_comp_call.update_layout(
        title=f'Comparaison des Calls (Maturité: {closest_maturity} mois)<br>Profil {profil["nom"]}',
        xaxis_title='Strike ($)',
        yaxis_title='Prix de l\'option ($)',
        hovermode='x unified',
        height=600
    )

    fig_comp_call.show()
    print(f"📊 Graphique interactif: Comparaison Calls ({closest_maturity} mois) générée")

if 'put' in option_types_focus:
    fig_comp_put = go.Figure()

    fig_comp_put.add_trace(go.Scatter(
        x=df_comp['Strike'],
        y=df_comp['Put Européen'],
        name='Put Européen',
        mode='lines+markers',
        line=dict(color='blue', width=3)
    ))

    fig_comp_put.add_trace(go.Scatter(
        x=df_comp['Strike'],
        y=df_comp['Put Américain'],
        name='Put Américain',
        mode='lines+markers',
        line=dict(color='green', width=3)
    ))

    fig_comp_put.add_trace(go.Scatter(
        x=df_comp['Strike'],
        y=df_comp['Put Bermudéen'],
        name='Put Bermudéen',
        mode='lines+markers',
        line=dict(color='orange', width=3)
    ))

    fig_comp_put.add_trace(go.Scatter(
        x=df_comp['Strike'],
        y=df_comp['Put Asiatique'],
        name='Put Asiatique',
        mode='lines+markers',
        line=dict(color='purple', width=3, dash='dash')
    ))

    fig_comp_put.add_vline(x=S0, line_dash="dash", line_color="red",
                          annotation_text=f"Prix actuel: ${S0:.2f}")

    fig_comp_put.update_layout(
        title=f'Comparaison des Puts (Maturité: {closest_maturity} mois)<br>Profil {profil["nom"]}',
        xaxis_title='Strike ($)',
        yaxis_title='Prix de l\'option ($)',
        hovermode='x unified',
        height=600
    )

    fig_comp_put.show()
    print(f"📊 Graphique interactif: Comparaison Puts ({closest_maturity} mois) générée")

print()

# ───────────────────────────────────────────────────────────────────────────
# 6.3: Greeks (Sensibilités)
# ───────────────────────────────────────────────────────────────────────────

if 'call' in option_types_focus and 'Call Delta' in df_comp.columns:
    # Greeks pour Calls
    fig_greeks_call = make_subplots(
        rows=2, cols=2,
        subplot_titles=('Delta (Sensibilité au prix)', 'Gamma (Sensibilité du Delta)',
                       'Vega (Sensibilité à la volatilité)', 'Theta (Décroissance temporelle)'),
        vertical_spacing=0.12,
        horizontal_spacing=0.1
    )

    # Delta
    fig_greeks_call.add_trace(
        go.Scatter(x=df_comp['Strike'], y=df_comp['Call Delta'],
                  name='Delta', mode='lines+markers', line=dict(color='blue', width=3)),
        row=1, col=1
    )
    fig_greeks_call.add_hline(y=0.5, line_dash="dash", line_color="gray", row=1, col=1)

    # Gamma
    fig_greeks_call.add_trace(
        go.Scatter(x=df_comp['Strike'], y=df_comp['Call Gamma'],
                  name='Gamma', mode='lines+markers', line=dict(color='green', width=3)),
        row=1, col=2
    )

    # Vega
    fig_greeks_call.add_trace(
        go.Scatter(x=df_comp['Strike'], y=df_comp['Call Vega'],
                  name='Vega', mode='lines+markers', line=dict(color='orange', width=3)),
        row=2, col=1
    )

    # Theta
    fig_greeks_call.add_trace(
        go.Scatter(x=df_comp['Strike'], y=df_comp['Call Theta'],
                  name='Theta', mode='lines+markers', line=dict(color='red', width=3)),
        row=2, col=2
    )

    # Ligne verticale pour prix actuel sur tous les subplots
    for row in [1, 2]:
        for col in [1, 2]:
            fig_greeks_call.add_vline(x=S0, line_dash="dash", line_color="gray",
                                     row=row, col=col)

    fig_greeks_call.update_xaxes(title_text="Strike ($)", row=2, col=1)
    fig_greeks_call.update_xaxes(title_text="Strike ($)", row=2, col=2)

    fig_greeks_call.update_layout(
        title_text=f"Greeks des Calls Européens (Maturité: {closest_maturity} mois)<br>Profil {profil['nom']}",
        height=800,
        showlegend=False
    )

    fig_greeks_call.show()
    print("📊 Graphique interactif: Greeks Calls générés")

if 'put' in option_types_focus and 'Put Delta' in df_comp.columns:
    # Greeks pour Puts
    fig_greeks_put = make_subplots(
        rows=2, cols=2,
        subplot_titles=('Delta (Sensibilité au prix)', 'Gamma (Sensibilité du Delta)',
                       'Vega (Sensibilité à la volatilité)', 'Theta (Décroissance temporelle)'),
        vertical_spacing=0.12,
        horizontal_spacing=0.1
    )

    fig_greeks_put.add_trace(
        go.Scatter(x=df_comp['Strike'], y=df_comp['Put Delta'],
                  name='Delta', mode='lines+markers', line=dict(color='blue', width=3)),
        row=1, col=1
    )
    fig_greeks_put.add_hline(y=-0.5, line_dash="dash", line_color="gray", row=1, col=1)

    fig_greeks_put.add_trace(
        go.Scatter(x=df_comp['Strike'], y=df_comp['Put Gamma'],
                  name='Gamma', mode='lines+markers', line=dict(color='green', width=3)),
        row=1, col=2
    )

    fig_greeks_put.add_trace(
        go.Scatter(x=df_comp['Strike'], y=df_comp['Put Vega'],
                  name='Vega', mode='lines+markers', line=dict(color='orange', width=3)),
        row=2, col=1
    )

    fig_greeks_put.add_trace(
        go.Scatter(x=df_comp['Strike'], y=df_comp['Put Theta'],
                  name='Theta', mode='lines+markers', line=dict(color='red', width=3)),
        row=2, col=2
    )

    for row in [1, 2]:
        for col in [1, 2]:
            fig_greeks_put.add_vline(x=S0, line_dash="dash", line_color="gray",
                                    row=row, col=col)

    fig_greeks_put.update_xaxes(title_text="Strike ($)", row=2, col=1)
    fig_greeks_put.update_xaxes(title_text="Strike ($)", row=2, col=2)

    fig_greeks_put.update_layout(
        title_text=f"Greeks des Puts Européens (Maturité: {closest_maturity} mois)<br>Profil {profil['nom']}",
        height=800,
        showlegend=False
    )

    fig_greeks_put.show()
    print("📊 Graphique interactif: Greeks Puts générés")

print()

# ───────────────────────────────────────────────────────────────────────────
# 6.4: Heatmap Moneyness vs Maturité
# ───────────────────────────────────────────────────────────────────────────

if 'call' in option_types_focus:
    # Pivot pour heatmap
    pivot_call = df_results.pivot_table(
        values='Call Européen',
        index='Strike',
        columns='Maturité (mois)',
        aggfunc='mean'
    )

    fig_heatmap_call = go.Figure(data=go.Heatmap(
        z=pivot_call.values,
        x=pivot_call.columns,
        y=pivot_call.index,
        colorscale='Viridis',
        colorbar=dict(title="Prix Call ($)")
    ))

    fig_heatmap_call.update_layout(
        title=f'Heatmap: Prix Call Européen selon Strike et Maturité<br>Profil {profil["nom"]}',
        xaxis_title='Maturité (mois)',
        yaxis_title='Strike ($)',
        height=600
    )

    fig_heatmap_call.show()
    print("📊 Graphique interactif: Heatmap Call générée")

if 'put' in option_types_focus:
    pivot_put = df_results.pivot_table(
        values='Put Européen',
        index='Strike',
        columns='Maturité (mois)',
        aggfunc='mean'
    )

    fig_heatmap_put = go.Figure(data=go.Heatmap(
        z=pivot_put.values,
        x=pivot_put.columns,
        y=pivot_put.index,
        colorscale='Reds',
        colorbar=dict(title="Prix Put ($)")
    ))

    fig_heatmap_put.update_layout(
        title=f'Heatmap: Prix Put Européen selon Strike et Maturité<br>Profil {profil["nom"]}',
        xaxis_title='Maturité (mois)',
        yaxis_title='Strike ($)',
        height=600
    )

    fig_heatmap_put.show()
    print("📊 Graphique interactif: Heatmap Put générée")

print()

# ═══════════════════════════════════════════════════════════════════════════
# SECTION 7: ANALYSE COMPARATIVE ET RECOMMANDATIONS
# ═══════════════════════════════════════════════════════════════════════════

print("=" * 80)
print("  ANALYSE COMPARATIVE - OPTIONS EUROPÉENNES VS AMÉRICAINES")
print("=" * 80)
print()

if 'call' in option_types_focus:
    # Calcul de la prime américaine (différence entre américaine et européenne)
    df_results['Prime Américaine Call'] = df_results['Call Américain'] - df_results['Call Européen']

    print("📊 ANALYSE DES CALLS:")
    print("-" * 80)
    print(f"{'Strike':<15} {'Maturité':<15} {'Euro':<15} {'Américain':<15} {'Prime Am.':<15} {'Recommandation':<20}")
    print("-" * 80)

    for _, row in df_results.head(10).iterrows():
        strike = f"${row['Strike']:.2f}"
        maturity = f"{int(row['Maturité (mois)'])} mois"
        euro = f"${row['Call Européen']:.2f}"
        american = f"${row['Call Américain']:.2f}"
        prime = f"${row['Prime Américaine Call']:.4f}"

        # Recommandation basée sur la prime
        if row['Prime Américaine Call'] > 0.50:
            rec = "Américain préférable"
        elif row['Prime Américaine Call'] > 0.10:
            rec = "Américain légèrement +"
        else:
            rec = "Européen suffisant"

        print(f"{strike:<15} {maturity:<15} {euro:<15} {american:<15} {prime:<15} {rec:<20}")

    print()

    # Statistiques agrégées
    avg_prime_call = df_results['Prime Américaine Call'].mean()
    print(f"💡 Prime américaine moyenne pour Calls: ${avg_prime_call:.4f}")
    print(f"   → L'exercice anticipé {'vaut' if avg_prime_call > 0.20 else 'ne vaut pas vraiment'} le surcoût")
    print()

if 'put' in option_types_focus:
    df_results['Prime Américaine Put'] = df_results['Put Américain'] - df_results['Put Européen']

    print("📊 ANALYSE DES PUTS:")
    print("-" * 80)
    print(f"{'Strike':<15} {'Maturité':<15} {'Euro':<15} {'Américain':<15} {'Prime Am.':<15} {'Recommandation':<20}")
    print("-" * 80)

    for _, row in df_results.head(10).iterrows():
        strike = f"${row['Strike']:.2f}"
        maturity = f"{int(row['Maturité (mois)'])} mois"
        euro = f"${row['Put Européen']:.2f}"
        american = f"${row['Put Américain']:.2f}"
        prime = f"${row['Prime Américaine Put']:.4f}"

        if row['Prime Américaine Put'] > 0.50:
            rec = "Américain préférable"
        elif row['Prime Américaine Put'] > 0.10:
            rec = "Américain légèrement +"
        else:
            rec = "Européen suffisant"

        print(f"{strike:<15} {maturity:<15} {euro:<15} {american:<15} {prime:<15} {rec:<20}")

    print()

    avg_prime_put = df_results['Prime Américaine Put'].mean()
    print(f"💡 Prime américaine moyenne pour Puts: ${avg_prime_put:.4f}")
    print(f"   → L'exercice anticipé {'vaut' if avg_prime_put > 0.20 else 'ne vaut pas vraiment'} le surcoût")
    print()

# ═══════════════════════════════════════════════════════════════════════════
# SECTION 8: RECOMMANDATIONS PERSONNALISÉES POUR L'INVESTISSEUR
# ═══════════════════════════════════════════════════════════════════════════

print("=" * 80)
print(f"  RECOMMANDATIONS POUR PROFIL: {profil['nom']}")
print("=" * 80)
print()

# Identification des meilleures options selon le profil
if PROFIL_INVESTISSEUR == 1:  # COUVERTURE
    print("🎯 STRATÉGIE DE COUVERTURE (HEDGING):")
    print()
    print("   Vous détenez des actions Nintendo et voulez vous protéger contre une baisse.")
    print()

    # Meilleur Put pour protection
    best_hedge = df_results[df_results['Status'] == 'ATM'].nsmallest(3, 'Maturité (mois)')

    print("   📋 OPTIONS RECOMMANDÉES (Protective Puts):")
    for i, (idx, row) in enumerate(best_hedge.iterrows(), 1):
        print(f"   {i}. Put Américain")
        print(f"      - Strike: ${row['Strike']:.2f} ({row['Status']})")
        print(f"      - Maturité: {int(row['Maturité (mois)'])} mois")
        print(f"      - Prix: ${row['Put Américain']:.2f}")
        print(f"      - Delta: {row['Put Delta']:.3f} (Couverture de {abs(row['Put Delta'])*100:.1f}%)")
        print(f"      - Coût pour 100 actions: ${row['Put Américain']*100:.2f}")
        print()

    print("   💡 CONSEIL:")
    print("      - Acheter 1 put par 100 actions détenues")
    print("      - Privilégier un strike ATM ou légèrement OTM pour réduire le coût")
    print("      - Renouveler tous les 3-6 mois (rolling hedge)")
    print()

elif PROFIL_INVESTISSEUR == 2:  # HAUSSIER
    print("🎯 STRATÉGIE SPÉCULATIVE HAUSSIÈRE:")
    print()
    print("   Vous anticipez une hausse du prix de Nintendo et voulez profiter de l'effet de levier.")
    print()

    # Meilleurs Calls pour spéculation
    best_calls = df_results[df_results['Status'].isin(['ATM', 'OTM'])].nsmallest(5, 'Call Européen')

    print("   📋 OPTIONS RECOMMANDÉES (Long Calls):")
    for i, (idx, row) in enumerate(best_calls.iterrows(), 1):
        leverage = S0 / row['Call Européen'] if row['Call Européen'] > 0 else 0
        breakeven = row['Strike'] + row['Call Européen']
        required_move = ((breakeven / S0) - 1) * 100

        print(f"   {i}. Call Européen")
        print(f"      - Strike: ${row['Strike']:.2f} ({row['Status']})")
        print(f"      - Maturité: {int(row['Maturité (mois)'])} mois")
        print(f"      - Prix: ${row['Call Européen']:.2f}")
        print(f"      - Delta: {row['Call Delta']:.3f}")
        print(f"      - Effet de levier: {leverage:.1f}x")
        print(f"      - Point mort: ${breakeven:.2f} (hausse de {required_move:.1f}% nécessaire)")
        print()

    print("   💡 CONSEIL:")
    print("      - Privilégier des calls ATM ou légèrement OTM pour bon équilibre coût/levier")
    print("      - Maturité 6-12 mois pour laisser le temps à la hausse de se matérialiser")
    print(f"      - Risque limité à la prime payée (max ${best_calls.iloc[0]['Call Européen']:.2f} par option)")
    print("      - Potentiel de gain illimité")
    print()

elif PROFIL_INVESTISSEUR == 3:  # BAISSIER
    print("🎯 STRATÉGIE SPÉCULATIVE BAISSIÈRE:")
    print()
    print("   Vous anticipez une baisse du prix de Nintendo.")
    print()

    best_puts = df_results[df_results['Status'].isin(['ATM', 'OTM'])].nsmallest(5, 'Put Européen')

    print("   📋 OPTIONS RECOMMANDÉES (Long Puts):")
    for i, (idx, row) in enumerate(best_puts.iterrows(), 1):
        leverage = S0 / row['Put Européen'] if row['Put Européen'] > 0 else 0
        breakeven = row['Strike'] - row['Put Européen']
        required_move = ((S0 / breakeven) - 1) * 100

        print(f"   {i}. Put Européen")
        print(f"      - Strike: ${row['Strike']:.2f} ({row['Status']})")
        print(f"      - Maturité: {int(row['Maturité (mois)'])} mois")
        print(f"      - Prix: ${row['Put Européen']:.2f}")
        print(f"      - Delta: {row['Put Delta']:.3f}")
        print(f"      - Effet de levier: {leverage:.1f}x")
        print(f"      - Point mort: ${breakeven:.2f} (baisse de {required_move:.1f}% nécessaire)")
        print()

    print("   💡 CONSEIL:")
    print("      - Puts ATM offrent bon équilibre sensibilité/coût")
    print("      - Maturité 3-6 mois suffisante pour mouvements baissiers")
    print(f"      - Risque limité à la prime (max ${best_puts.iloc[0]['Put Européen']:.2f})")
    print()

elif PROFIL_INVESTISSEUR == 4:  # REVENUS
    print("🎯 STRATÉGIE DE GÉNÉRATION DE REVENUS (COVERED CALLS):")
    print()
    print("   Vous détenez des actions Nintendo et voulez générer des revenus réguliers.")
    print()

    # Calls OTM courts termes
    covered_calls = df_results[
        (df_results['Status'].isin(['ATM', 'OTM'])) &
        (df_results['Maturité (mois)'] <= 3)
    ].sort_values('Maturité (mois)')

    print("   📋 CALLS À VENDRE (Covered Calls):")
    for i, (idx, row) in enumerate(covered_calls.head(5).iterrows(), 1):
        annualized_return = (row['Call Européen'] / S0) * (12 / row['Maturité (mois)']) * 100

        print(f"   {i}. Vendre Call Européen")
        print(f"      - Strike: ${row['Strike']:.2f} ({row['Status']}) - {((row['Strike']/S0)-1)*100:.1f}% au-dessus du prix actuel")
        print(f"      - Maturité: {int(row['Maturité (mois)'])} mois")
        print(f"      - Prime reçue: ${row['Call Européen']:.2f}")
        print(f"      - Revenu annualisé: {annualized_return:.2f}% du prix de l'action")
        print(f"      - Pour 100 actions: ${row['Call Européen']*100:.2f} de revenu")
        print()

    print("   💡 CONSEIL:")
    print("      - Vendre des calls OTM (5-10% au-dessus du prix actuel)")
    print("      - Renouveler chaque mois ou trimestre")
    print("      - Accepter que les actions puissent être appelées si prix > strike")
    print("      - Combiner avec dividendes Nintendo pour revenu total optimisé")
    print()

else:  # VOLATILITÉ
    print("🎯 STRATÉGIE SUR VOLATILITÉ (STRADDLE/STRANGLE):")
    print()
    print("   Vous anticipez un mouvement important sans savoir la direction.")
    print()

    # Straddle ATM
    straddles = df_results[df_results['Status'] == 'ATM'].copy()
    straddles['Straddle Cost'] = straddles['Call Européen'] + straddles['Put Européen']
    straddles['Breakeven Low'] = straddles['Strike'] - straddles['Straddle Cost']
    straddles['Breakeven High'] = straddles['Strike'] + straddles['Straddle Cost']

    print("   📋 STRADDLES RECOMMANDÉS (Call + Put ATM):")
    for i, (idx, row) in enumerate(straddles.head(3).iterrows(), 1):
        move_required = (row['Straddle Cost'] / S0) * 100

        print(f"   {i}. Straddle (Achat Call + Put)")
        print(f"      - Strike: ${row['Strike']:.2f}")
        print(f"      - Maturité: {int(row['Maturité (mois)'])} mois")
        print(f"      - Coût total: ${row['Straddle Cost']:.2f}")
        print(f"      - Points morts: ${row['Breakeven Low']:.2f} - ${row['Breakeven High']:.2f}")
        print(f"      - Mouvement requis: ±{move_required:.1f}%")
        print(f"      - Vega (sensibilité volatilité): {row['Call Vega']:.3f}")
        print()

    print("   💡 CONSEIL:")
    print("      - Profitable si mouvement > coût du straddle")
    print("      - Bénéficie d'une hausse de volatilité implicite")
    print("      - À privilégier avant annonces importantes (résultats, nouveaux jeux)")
    print()

# ═══════════════════════════════════════════════════════════════════════════
# SECTION 9: ANALYSE DE SCÉNARIOS
# ═══════════════════════════════════════════════════════════════════════════

print("=" * 80)
print("  ANALYSE DE SCÉNARIOS - PROFIT & LOSS")
print("=" * 80)
print()

# Sélection d'une option représentative pour analyse P&L
if 'call' in option_types_focus:
    # Call ATM, maturité médiane
    atm_calls = df_results[df_results['Status'] == 'ATM']
    if not atm_calls.empty:
        representative_call = atm_calls.iloc[len(atm_calls)//2]
        K_call = representative_call['Strike']
        premium_call = representative_call['Call Européen']
        T_call = representative_call['Maturité (années)']

        # Plage de prix à maturité
        price_range = np.linspace(S0 * 0.5, S0 * 1.5, 100)

        # Calcul du P&L pour Long Call
        payoff_call = np.maximum(price_range - K_call, 0) - premium_call

        # Breakeven
        breakeven_call = K_call + premium_call

        # Visualisation
        fig_pl_call = go.Figure()

        fig_pl_call.add_trace(go.Scatter(
            x=price_range,
            y=payoff_call,
            name='Long Call P&L',
            line=dict(color='green', width=3),
            fill='tozeroy',
            fillcolor='rgba(0,255,0,0.1)'
        ))

        fig_pl_call.add_hline(y=0, line_dash="solid", line_color="black", line_width=2)
        fig_pl_call.add_vline(x=S0, line_dash="dash", line_color="blue",
                             annotation_text=f"Prix actuel: ${S0:.2f}")
        fig_pl_call.add_vline(x=breakeven_call, line_dash="dash", line_color="red",
                             annotation_text=f"Point mort: ${breakeven_call:.2f}")

        fig_pl_call.update_layout(
            title=f'Profit & Loss: Long Call (Strike ${K_call:.2f}, Prime ${premium_call:.2f})<br>Profil {profil["nom"]} reverdure',
            xaxis_title='Prix de Nintendo à maturité ($)',
            yaxis_title='Profit / Perte ($)',
            hovermode='x',
            height=600
        )

        fig_pl_call.show()
        print(f"📊 Graphique interactif: P&L Long Call (Strike ${K_call:.2f}) généré")
    else:
        print("💡 Pas de Call ATM trouvé pour l'analyse P&L pour le profil actuel.")

if 'put' in option_types_focus:
    atm_puts = df_results[df_results['Status'] == 'ATM']
    if not atm_puts.empty:
        representative_put = atm_puts.iloc[len(atm_puts)//2]
        K_put = representative_put['Strike']
        premium_put = representative_put['Put Européen']
        T_put = representative_put['Maturité (années)']

        price_range = np.linspace(S0 * 0.5, S0 * 1.5, 100)

        payoff_put = np.maximum(K_put - price_range, 0) - premium_put
        breakeven_put = K_put - premium_put

        fig_pl_put = go.Figure()

        fig_pl_put.add_trace(go.Scatter(
            x=price_range,
            y=payoff_put,
            name='Long Put P&L',
            line=dict(color='red', width=3),
            fill='tozeroy',
            fillcolor='rgba(255,0,0,0.1)'
        ))

        fig_pl_put.add_hline(y=0, line_dash="solid", line_color="black", line_width=2)
        fig_pl_put.add_vline(x=S0, line_dash="dash", line_color="blue",
                            annotation_text=f"Prix actuel: ${S0:.2f}")
        fig_pl_put.add_vline(x=breakeven_put, line_dash="dash", line_color="red",
                            annotation_text=f"Point mort: ${breakeven_put:.2f}")

        fig_pl_put.update_layout(
            title=f'Profit & Loss: Long Put (Strike ${K_put:.2f}, Prime ${premium_put:.2f})<br>Profil {profil["nom"]}',
            xaxis_title='Prix de Nintendo à maturité ($)',
            yaxis_title='Profit / Perte ($)',
            hovermode='x',
            height=600
        )

        fig_pl_put.show()
        print(f"📊 Graphique interactif: P&L Long Put (Strike ${K_put:.2f}) généré")
    else:
        print("💡 Pas de Put ATM trouvé pour l'analyse P&L pour le profil actuel.")

print()

# ═══════════════════════════════════════════════════════════════════════════
# SECTION 10: TABLEAU RÉCAPITULATIF FINAL
# ═══════════════════════════════════════════════════════════════════════════

print("=" * 80)
print("  TABLEAU RÉCAPITULATIF - MEILLEURES OPPORTUNITÉS")
print("=" * 80)
print()

# Création d'un tableau récapitulatif selon le profil
summary_options = []

if 'call' in option_types_focus:
    # Top 3 Calls selon le profil
    if PROFIL_INVESTISSEUR in [2, 4]:  # Haussier ou Revenus
        top_calls = df_results.nsmallest(3, 'Call Européen')
        for _, row in top_calls.iterrows():
            summary_options.append({
                'Type': 'Call Européen',
                'Strike': f"${row['Strike']:.2f}",
                'Maturité': f"{int(row['Maturité (mois)'])} mois",
                'Prix': f"${row['Call Européen']:.2f}",
                'Delta': f"{row['Call Delta']:.3f}",
                'Status': row['Status'],
                'Usage': 'Spéculation haussière' if PROFIL_INVESTISSEUR == 2 else 'Vente couverte'
            })

if 'put' in option_types_focus:
    # Top 3 Puts selon le profil
    if PROFIL_INVESTISSEUR in [1, 3]:  # Couverture ou Baissier
        top_puts = df_results.nsmallest(3, 'Put Européen')
        for _, row in top_puts.iterrows():
            summary_options.append({
                'Type': 'Put Européen',
                'Strike': f"${row['Strike']:.2f}",
                'Maturité': f"{int(row['Maturité (mois)'])} mois",
                'Prix': f"${row['Put Européen']:.2f}",
                'Delta': f"{row['Put Delta']:.3f}",
                'Status': row['Status'],
                'Usage': 'Protection (Hedge)' if PROFIL_INVESTISSEUR == 1 else 'Spéculation baissière'
            })

if summary_options:
    df_summary = pd.DataFrame(summary_options)
    print(df_summary.to_string(index=False))
    print()

# ═══════════════════════════════════════════════════════════════════════════
# SECTION 11: CONSEILS FINAUX ET AVERTISSEMENTS
# ═══════════════════════════════════════════════════════════════════════════

print("=" * 80)
print("  CONSEILS FINAUX POUR L'INVESTISSEUR")
print("=" * 80)
print()

print(f"🎯 PROFIL: {profil['nom']}")
print(f"   Stratégie principale: {profil['strategie_principale']}")
print()

print("💡 POINTS CLÉS À RETENIR:")
print()
print("   1. TIMING:")
print("      - Les options sont des actifs à durée de vie limitée")
print(f"      - Horizon recommandé: {profil['horizon_typique']}")
print("      - La valeur temps décroît exponentiellement proche de la maturité (Theta)")
print()

print("   2. GESTION DU RISQUE:")
print("      - Options d'achat (Calls/Puts): Risque limité à la prime payée")
print("      - Options de vente: Risque potentiellement illimité (ne pas vendre d'options nues)")
print("      - Utiliser les Greeks pour surveiller les sensibilités")
print(f"      - Delta target pour votre profil: {profil['delta_target']}")
print()

print("   3. VOLATILITÉ:")
print(f"      - Volatilité historique Nintendo: {volatility_hist*100:.2f}%")
print("      - Vega positif: vous profitez d'une hausse de volatilité")
print("      - Considérer la volatilité implicite du marché (non capturée ici)")
print()

print("   4. COÛTS DE TRANSACTION:")
print("      - Les prix indiqués sont théoriques (mid-market)")
print("      - Prévoir spread bid-ask + commissions courtier")
print("      - Impact sur petites positions peut être significatif")
print()

print("   5. FISCALITÉ:")
print("      - Traitement fiscal des options peut différer des actions")
print("      - Consulter un conseiller fiscal pour votre juridiction")
print()

print("   6. DIVERSIFICATION:")
print("      - Ne pas concentrer tout le capital sur options d'une seule société")
print("      - Les options sont des produits dérivés à risque élevé")
print("      - Combiner avec stratégie diversifiée sur sous-jacents")
print()

print("⚠️  AVERTISSEMENTS:")
print()
print("   - Les modèles utilisés (Black-Scholes, Binomial) reposent sur des hypothèses")
print("     simplificatrices (volatilité constante, pas de dividendes, etc.)")
print("   - Les performances passées ne préjugent pas des performances futures")
print("   - Les prix réels de marché peuvent différer des prix théoriques")
print("   - Options = produits complexes réservés à investisseurs avertis")
print("   - Toujours comprendre parfaitement un produit avant d'investir")
print()

print("=" * 80)
print("  FIN DE L'ANALYSE - OPTION PRICING")
print("=" * 80)
print()

print("📊 FICHIERS DE SORTIE RECOMMANDÉS:")
print("   - Exporter df_results en CSV pour analyse approfondie")
print("   - Sauvegarder les graphiques interactifs en HTML")
print("   - Créer un rapport PDF avec les recommandations personnalisées")
print()

# Option d'export (décommenter si nécessaire)
# df_results.to_csv('nintendo_options_analysis.csv', index=False)
# fig_3d_call.write_html('nintendo_call_surface.html')
# fig_3d_put.write_html('nintendo_put_surface.html')

print("✅ Analyse complète terminée avec succès!")